/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triangulo;

import javax.swing.JOptionPane;

/**
 *
 * @author ESFOT
 */
public class Triangulos extends javax.swing.JFrame {

    /**
     * Creates new form Triangulos
     */
    public Triangulos() {
        initComponents();
        
        String TipoTriangulo= cmbTipoTriangulo.getSelectedItem().toString();
        if(TipoTriangulo.equals("Rectangulo")){
              
          }else  if(TipoTriangulo.equals("Isoceles")){
              
          }else if(TipoTriangulo.equals("Escaleno")){
              
          }else if(TipoTriangulo.equals("Equilatero")){
              
          } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblLadoA = new javax.swing.JLabel();
        lblLadoB = new javax.swing.JLabel();
        lblLadoC = new javax.swing.JLabel();
        txtLadoA = new javax.swing.JTextField();
        txtLadoB = new javax.swing.JTextField();
        txtLadoC = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        cmbTipoTriangulo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        txtPerimetro = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Datos del Triangulo");

        lblLadoA.setText("Lado a:");

        lblLadoB.setText("Lado b:");

        lblLadoC.setText("Lado c:");

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        cmbTipoTriangulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rectangulo", "Isoceles", "Escaleno", "Equilatero" }));
        cmbTipoTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoTrianguloActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione el tipo de triangulo");

        jLabel3.setText("Perimetro:");

        jLabel4.setText("Area:");

        jLabel5.setText("Altura:");

        jLabel6.setText("Resultados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblLadoA)
                                            .addComponent(lblLadoB))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtLadoB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(cmbTipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtLadoA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(156, 156, 156))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnVerificar)
                                        .addGap(260, 260, 260))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(lblLadoC)
                                .addGap(18, 18, 18)
                                .addComponent(txtLadoC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(txtPerimetro)
                        .addComponent(txtArea)))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLadoA)
                    .addComponent(txtLadoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLadoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLadoB)
                            .addComponent(cmbTipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLadoC)
                            .addComponent(txtLadoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnVerificar)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        double a=Double.valueOf(txtLadoA.getText());
        double b=Double.valueOf(txtLadoB.getText());
        double c=Double.valueOf(txtLadoC.getText());
        
        if(Estriangulo()){
         
            System.out.println("Si es triangulo"); 
        }else{
            System.out.println("No es triangulo");
           
            JOptionPane.showMessageDialog(rootPane,"Los datos no corresponden a un triangulo ");
            txtLadoA.setText("");
            txtLadoB.setText("");
            txtLadoC.setText("");
        }
        
        String TipoTriangulo= cmbTipoTriangulo.getSelectedItem().toString();
        
        if(Estriangulo()){
            
            Figura f;
          if(TipoTriangulo.equals("Rectangulo")){
             double aR=Double.valueOf(txtLadoA.getText());
             double bR=Double.valueOf(txtLadoB.getText());
             double cR=Double.valueOf(txtLadoC.getText());
              f =new TRectangulo(aR,bR,cR); 
              txtArea.setText(String.valueOf(f.Area()));
              txtPerimetro.setText(String.valueOf(f.Perimetro()));
              txtAltura.setText(String.valueOf(f.Altura()));
              txtLadoA.setText("");
            txtLadoB.setText("");
            txtLadoC.setText("");
              
          }else  if(TipoTriangulo.equals("Isoceles")){
               double aI=Double.valueOf(txtLadoA.getText());
             double bI=Double.valueOf(txtLadoB.getText());
             
              f =new TIsoceles(aI,bI);
             txtArea.setText(String.valueOf(f.Area()));
              txtPerimetro.setText(String.valueOf(f.Perimetro()));
              txtAltura.setText(String.valueOf(f.Altura())); 
              txtLadoA.setText("");
            txtLadoB.setText("");
            txtLadoC.setText("");
          }else if(TipoTriangulo.equals("Escaleno")){
               double aEs=Double.valueOf(txtLadoA.getText());
             double bEs=Double.valueOf(txtLadoB.getText());
             double cEs=Double.valueOf(txtLadoC.getText());
              f =new TEscaleno(aEs,bEs,cEs);
              txtArea.setText(String.valueOf(f.Area()));
              txtPerimetro.setText(String.valueOf(f.Perimetro()));
              txtAltura.setText(String.valueOf(f.Altura()));
              txtLadoA.setText("");
            txtLadoB.setText("");
            txtLadoC.setText("");
          }else if(TipoTriangulo.equals("Equilatero")){
               double aEq=Double.valueOf(txtLadoA.getText());
              f =new TEquilatero(aEq);
              txtArea.setText(String.valueOf(f.Area()));
              txtPerimetro.setText(String.valueOf(f.Perimetro()));
              txtAltura.setText(String.valueOf(f.Altura()));
              txtLadoA.setText("");
            txtLadoB.setText("");
            txtLadoC.setText("");
          } 
        }
        
    }//GEN-LAST:event_btnVerificarActionPerformed
private boolean Estriangulo(){
    boolean EsTriangulo=false;
        double a=Double.valueOf(txtLadoA.getText());
        double b=Double.valueOf(txtLadoB.getText());
        double c=Double.valueOf(txtLadoC.getText());
     if(a+b>c){
      if(b+c>a){
       if(c+a>b){
        EsTriangulo =true;
      }    
      }    
     }   
    
    return EsTriangulo;  
}
    
    
    
    private void cmbTipoTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoTrianguloActionPerformed
        
        String TipoTriangulo= cmbTipoTriangulo.getSelectedItem().toString();
        
          if(TipoTriangulo.equals("Rectangulo")){
            txtLadoA.setVisible(true);
            txtLadoB.setVisible(true);
            txtLadoC.setVisible(true);
            lblLadoA.setVisible(true);
            lblLadoB.setVisible(true);
            lblLadoC.setVisible(true);
            
          }else  if(TipoTriangulo.equals("Isoceles")){
             txtLadoA.setVisible(true);
            txtLadoB.setVisible(true);
            txtLadoC.setVisible(false);
            lblLadoA.setVisible(true);
            lblLadoB.setVisible(true);
            lblLadoC.setVisible(false);
           
          }else if(TipoTriangulo.equals("Escaleno")){
            txtLadoA.setVisible(true);
            txtLadoB.setVisible(true);
            txtLadoC.setVisible(true);
            lblLadoA.setVisible(true);
            lblLadoB.setVisible(true);
            lblLadoC.setVisible(true);  
            
          }else if(TipoTriangulo.equals("Equilatero")){
            txtLadoA.setVisible(true);
            txtLadoB.setVisible(false);
            txtLadoC.setVisible(false);
            lblLadoA.setVisible(true);
            lblLadoB.setVisible(false);
            lblLadoC.setVisible(false);
           
        }
        
    }//GEN-LAST:event_cmbTipoTrianguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triangulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JComboBox<String> cmbTipoTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblLadoA;
    private javax.swing.JLabel lblLadoB;
    private javax.swing.JLabel lblLadoC;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtLadoA;
    private javax.swing.JTextField txtLadoB;
    private javax.swing.JTextField txtLadoC;
    private javax.swing.JTextField txtPerimetro;
    // End of variables declaration//GEN-END:variables
}
